### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by xee5ch** [ComplianceAsCode/libreSCAP#9]
Is this project still active?

**Comment by shawndwells** [comment]
No :(

**Comment by xee5ch** [comment]
So for the foreseeable future, ongoing SCAP work for RedHat/ComplianceAsCode teams will be on the reference OpenSCAP implementation?

**Comment by shawndwells** [comment]
Most of the LibreSCAP crew (@isimluk , @redhatrises , myself) are no longer with Red Hat. Our current work does use SCAP but the implementation hasn't been upstreamed/open sourced yet.

@matejak or @yuumasato of Red Hat may be able to comment on their OpenSCAP plans though!

**Comment by xee5ch** [comment]
Thanks for the clarifying comments, that helps! I'll close for now unless they want to reopen and comment.

**Comment by matejak** [comment]
https://github.com/OpenSCAP/openscap is indeed alive, and developers are actively working on it. Obviously the tool deserves a facelift in order to continue to be an adequate tool for automated compliance checks, but we don't think that we need to start a new project from scratch to address current and expected future issues.
